name: "Nightly merge"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9

      - name: ⬇ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🔀 Merge main into dev
        uses: robotology/gh-action-nightly-merge@81570ba03dd370f582bd3f52d47672d29191829f # v1.5.2
        with:
          stable_branch: "main"
          development_branch: "dev"
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔀 Merge bugfix into dev
        uses: robotology/gh-action-nightly-merge@81570ba03dd370f582bd3f52d47672d29191829f # v1.5.2
        with:
          stable_branch: "bugfix"
          development_branch: "dev"
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔀 Merge next into dev
        uses: robotology/gh-action-nightly-merge@81570ba03dd370f582bd3f52d47672d29191829f # v1.5.2
        with:
          stable_branch: "next"
          development_branch: "dev"
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
