name: "Pull Request Automation"
on:
  pull_request_target:
    types: ["opened"]

jobs:
  pr-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9

      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: OctoPrint/actions/pr-validation@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
